'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false

[buf]
disabled = true

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](bold green)'
vimcmd_replace_one_symbol	= '[<](bold purple)'
vimcmd_replace_symbol	= '[<](bold purple)'
vimcmd_visual_symbol= '[<](bold yellow)'

[cmd_duration]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 1

[gcloud]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[kubernetes]
disabled = false
