# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](bold green)'
vimcmd_replace_one_symbol	= '[<](bold purple)'
vimcmd_replace_symbol	= '[<](bold purple)'
vimcmd_visual_symbol= '[<](bold yellow)'

[cmd_duration]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 1
